---
title: "Lab 00 - Hello IDS!"
author: "Ethan Wallis"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(tibble)
```


### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Juliet", "Zack", "Miles", 
           "Freddie", "member 4"),
  github_username = c("juleshevlin-oss", "ZackLukUoE", "Milesmiller100636", 
                      "Fredrusson", "username 4"), 
  colour = c("purple", "blue", "grey", 
             "lightblue", "colour 4"),
  hobby = c("crochet", "sport", "golf", 
            "golf", "hobby 4"),
  favourite_number = c(7, 9, 26, 10, NA)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

A graph showing the groups favourite number represented in a bar graph by their favourite colour.

